-- Synthetic local migration test fixture only. No production accounts, password hashes or media.
CREATE SCHEMA auth;
CREATE SCHEMA storage;
CREATE TABLE auth.users (id uuid PRIMARY KEY, email text, encrypted_password text, raw_user_meta_data jsonb, created_at timestamptz);
CREATE TABLE auth.identities (id uuid PRIMARY KEY, user_id uuid REFERENCES auth.users, provider text, identity_data jsonb);
CREATE TABLE public.profiles (id uuid PRIMARY KEY REFERENCES auth.users, username text, bio text, tags text[], avatar_url text);
CREATE TABLE public.posts (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id uuid REFERENCES public.profiles, caption text, media_url text, score numeric(18,4), created_at timestamptz);
CREATE TABLE public.private_messages (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sender_id uuid REFERENCES public.profiles, receiver_id uuid REFERENCES public.profiles, body text, payload bytea);
CREATE TABLE storage.buckets (id text PRIMARY KEY, name text, public boolean);
CREATE TABLE storage.objects (id uuid PRIMARY KEY, bucket_id text REFERENCES storage.buckets, name text, metadata jsonb, owner_id uuid, UNIQUE(bucket_id,name));
CREATE TABLE public.empty_records (id uuid PRIMARY KEY);
CREATE TABLE public."quoted""table" ("weird""column" text);
CREATE TABLE public.partitioned_records (id int, bucket int) PARTITION BY LIST(bucket);
CREATE TABLE public.partitioned_child PARTITION OF public.partitioned_records FOR VALUES IN(1);
INSERT INTO auth.users VALUES
('11111111-1111-1111-1111-111111111111','fixture1@example.invalid','fixture-only-not-a-valid-password-hash','{"username":"test_owl"}', '2026-10-05T01:00:00Z'),
('22222222-2222-2222-2222-222222222222','fixture2@example.invalid','fixture-only-not-a-valid-password-hash','{"username":"second_owl"}', '2026-10-05T02:00:00Z');
INSERT INTO auth.identities VALUES
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','11111111-1111-1111-1111-111111111111','email','{"email":"fixture1@example.invalid","email_verified":true}'),
('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb','22222222-2222-2222-2222-222222222222','google','{"sub":"fixture-provider-subject","email":"fixture2@example.invalid"}');
INSERT INTO public.profiles VALUES
('11111111-1111-1111-1111-111111111111','test_owl', E'Mongolian: Шөнө\nSecond line', ARRAY['night','day'], 'https://fixture.invalid/storage/avatar.jpg'),
('22222222-2222-2222-2222-222222222222','second_owl',NULL,ARRAY[]::text[],NULL);
INSERT INTO public.posts(user_id,caption,media_url,score,created_at) VALUES
('11111111-1111-1111-1111-111111111111',E'Hello\nWorld','https://fixture.invalid/private/post.jpg',1.2300,'2026-10-05T03:00:00+08:00'),
('22222222-2222-2222-2222-222222222222','Multilingual 🦉 Монгол',NULL,-99.0100,'2026-10-05T04:00:00Z');
INSERT INTO public.private_messages(sender_id,receiver_id,body,payload) VALUES
('11111111-1111-1111-1111-111111111111','22222222-2222-2222-2222-222222222222',E'Synthetic private\nmessage',decode('000102feff','hex'));
ALTER TABLE public.private_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY fixture_owner_policy ON public.private_messages FOR SELECT TO CURRENT_USER USING (true);
INSERT INTO storage.buckets VALUES ('private','private',false),('empty','empty',true);
INSERT INTO storage.objects VALUES ('cccccccc-cccc-cccc-cccc-cccccccccccc','private','../synthetic file.jpg','{"size":16,"mimetype":"image/jpeg"}','11111111-1111-1111-1111-111111111111');
INSERT INTO public."quoted""table" VALUES ('quoted'), (E'new\nline'), ('tab'||chr(9)||'value');
INSERT INTO public.partitioned_records VALUES (1,1),(2,1);
CREATE MATERIALIZED VIEW public.profile_summary AS SELECT count(*) AS users FROM public.profiles;
SELECT lo_from_bytea(90001,decode('48656c6c6f000a46697874757265','hex'));
SELECT nextval('public.posts_id_seq');
